### ISSUE TITLE
Integrate STOMP client

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/plant-controller#12]
The [Oslo greenhouse actuator](https://github.com/MarcoAmato/greenhouse_actuator) code receives STOMP protocol messages and waters the plants. The existing plant controller needs to have the same capability. The configuration proposed in PR #10 needs to be enhanced to map from plant number to pin number received on the STOMP protocol message.

**Comment by prasadtalasila** [comment]
#### Comment by Mikkel

I have looked at the STOMP client issue. I have copied the subscriber.py file and added the following to the config.yaml.template file 

``` yaml
external:
    stomp:
      actuator_id: [1, 2, 3]
      URL: "localhost.com"
      USER: "admin"
      PASS: "admin"
```

Am i going to add the connection part to STOMP inside the controller-1.py, such that it automatically connects if settings are given in the config.yaml? like the things they have is in their __main__.py?

**Comment by prasadtalasila** [comment]
No. Please add new `comm.py` in which you can add the STOMP client.
The client should take a callback hook (function) as argument. This callback  can be  `water_pump`.

**Comment by prasadtalasila** [comment]
You can bring out the water pumps code into `pumps.py` as a preparatory step. The necessary logic to map the local pump numbers to pin numbers / actuator IDs coming as STOMP messages can also be placed as a function inside `pumps.py`.

**Comment by prasadtalasila** [comment]
You can add a new function in `config.py` to map the actuator ID. The suggested config is

```yaml
  actuators:
    pump_1:
      id: 1
      schedule: "10:15"
    pump_2:
      id: 1
      schedule: "14:30"
    pump_3:
      id: 1
      schedule: "10:15"
```

**Comment by prasadtalasila** [comment]
If we only need include the pump pin, the configuration could be changed to

```yaml
  actuators:
    pump_1:
      pin: 1
      schedule: "10:15"
    pump_2:
      pin: 2
      schedule: "14:30"
    pump_3:
      pin: 3
      schedule: "10:15"
```
