### ISSUE TITLE
Create configuration for controller

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/plant-controller#4]
### Configuration of Greenhouse controller from Oslo

The RPi data collector (for sensors) and actuators (motors) has the following config files

https://github.com/sievericcardo/greenhouse-data-collector/blob/master/collector/config.ini.example

The topics on which the collector config is sent is

<img width="150" alt="Image" src="https://github.com/user-attachments/assets/c521b969-6515-4bc4-ba71-a6df95c73244" />
<img width="142" alt="Image" src="https://github.com/user-attachments/assets/656bcd1d-5dfa-4997-ad33-14538f530b5c" />

The communication protocol for exchanging is RabbitMQ and the configuration format for exchange is json.

## Draft Config

The current draft of the configuration in ini format is

```ini
[influx2]
url=http://169.254.48.238:8086
org=myOrg
token=xxxx

RabbitMQ configuration
[amqp]
url=localhost:5672
username=guest
password=guest
vhost=/
exchange=greenhouse_data

[plant]
sense-quality=[low,high]
sense=[temperature, humidity, light, moisture, water_level]
actuate=[water_pump, nutrient_pump]

[plant.1]
sense-quality=[low,high]
sense=[temperature, humidity, light, moisture, water_level]
actuate=[water_pump, nutrient_pump]

```

**Comment by prasadtalasila** [comment]
The [W3C WoT documentation](https://www.w3.org/WoT/documentation/), and [Thing Description](https://github.com/w3c/wot-thing-description/blob/main/explainer/Explainer11.md) fit nicely with the REST API paradigm Riccardo is developing..

**Comment by prasadtalasila** [comment]
From issue #6

```toml
# properties are sensors that can be read from a plant
# actions are actuators that can change the status of a plant for example by watering it
[[plants]]
plant-id="id-hash-1"
properties = ["temperature"]
actions = ["water_pump"]

[[plants]]
plant-id="id-hash-2"
properties = ["temperature"]
actions = ["water_pump"]

[[plants]]
plant-id="id-hash-3"
properties = ["temperature"]
actions = ["water_pump"]
```
