### ISSUE TITLE
Implement services configuration

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/plant-controller#6]
Add support for the following partial configuration.

```toml
[influx2]
url=http://localhost:5672
org=myOrg
bucket=myBucket
token=xxxx

# RabbitMQ configuration
[amqp]
url=localhost:5672
username=guest
password=guest
vhost=/

[plant.1]
properties = [temperature]
action=[water_pump]

[plant.1.temperature]
protocol=i2c
mux_port=0

[plant.1.water_pump]
protocol=i2c
mux_port=0
```
